// <auto-generated />
using System;
using DataSample.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataSample.Migrations
{
    [DbContext(typeof(TodoDataContext))]
    [Migration("20190418083314_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataSample.DataAccess.CategoriesToTodoItem", b =>
                {
                    b.Property<int>("CategoryId");

                    b.Property<int>("TodoItemId");

                    b.HasKey("CategoryId", "TodoItemId");

                    b.HasIndex("TodoItemId");

                    b.ToTable("CategoriesToTodoItems");
                });

            modelBuilder.Entity("DataSample.DataAccess.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DataSample.DataAccess.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DueDate");

                    b.Property<bool>("IsDone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("DataSample.DataAccess.CategoriesToTodoItem", b =>
                {
                    b.HasOne("DataSample.DataAccess.Category", "Category")
                        .WithMany("CategoriesToTodoItems")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_CategoriesToTodoItems_Categories");

                    b.HasOne("DataSample.DataAccess.TodoItem", "TodoItem")
                        .WithMany("CategoriesToTodoItems")
                        .HasForeignKey("TodoItemId")
                        .HasConstraintName("FK_CategoriesToTodoItems_TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
